### PR TITLE
Allow list to be passed as geo

### LINKED ISSUE #352: how to input multiple geo codes in pytrend.build_payload
I am trying to get a time-series GSV of one key word but in two different regions using the following code (it used to work when I collected the data for other key words a few months ago):
pytrend.build_payload(["Python"], cat=0, timeframe='all',geo='US-CA,US-TX',gprop='')
gsv = pytrend.interest_over_time()

Any help will be much appreciated.
the error code is as follows,
  File "C:\Python3\lib\site-packages\pytrends\request.py", line 120, in build_payload
    self._tokens()
  File "C:\Python3\lib\site-packages\pytrends\request.py", line 131, in _tokens
    trim_chars=4,
  File "C:\Python3\lib\site-packages\pytrends\request.py", line 101, in _get_data
    'response with code {0}.'.format(response.status_code), response=response)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400.

### PR DESCRIPTION
**Pull request by sv1990**
This allows passing multiple regions to be requested for the same keyword. This fixes  #352.

### CODE REVIEW

**Comment by emlazzarin** [comment]
@sv1990 are you okay rebasing this and reconfiguring a bit to match the new testing system?

**Comment by sv1990** [comment]
Hi @emlazzarin, I'll look into it later

**Comment by sv1990** [comment]
I think I messed up the rebase. The actual diff can be seen [here](https://github.com/GeneralMills/pytrends/compare/master...sv1990:pytrends:master). 

Should I maybe open a new pull request in the hope that github doesn't think anymore that I changed 34 files?

**Comment by sv1990** [comment]
I think I fixed it

**Comment by sv1990** [comment]
I had to change the values in the unrelated test `test_interest_by_region_city_resolution` so that all tests are now passing for me locally

**Review by Terseus — APPROVED** [review]

**Comment by Terseus** [comment]
LGTM, thanks @sv1990 !

**Comment by AlexYarkin** [comment]
Hi there! I think I still can't pas a list into geo, see below:

pytrends = TrendReq()
pytrends.build_payload(kw_list=['pizza'], geo=['US-NY', 'US-IL'])
df = pytrends.interest_over_time()

Traceback (most recent call last):

  File "C:\Users\alexandery\AppData\Local\Temp\ipykernel_37688\2385922720.py", line 2, in <module>
    pytrends.build_payload(kw_list=['pizza'], geo=['US-NY', 'US-IL'])

  File "C:\Users\alexandery\AppData\Roaming\Python\Python39\site-packages\pytrends\request.py", line 189, in build_payload
    self._tokens()

  File "C:\Users\alexandery\AppData\Roaming\Python\Python39\site-packages\pytrends\request.py", line 195, in _tokens
    widget_dicts = self._get_data(

  File "C:\Users\alexandery\AppData\Roaming\Python\Python39\site-packages\pytrends\request.py", line 160, in _get_data
    raise exceptions.ResponseError.from_response(response)

ResponseError: The request failed: Google returned a response with code 400

Any suggestions would be welcome! Thanks a lot

**Comment by Terseus** [comment]
@AlexYarkin I just checked and the feature still works for me, if you can provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) please open a new issue referencing this PR.

**Pull request merged**
