### PR TITLE
fix Pandas json._normalize import

### PR DESCRIPTION
**Pull request by emlazzarin**
This fixes issue #317.

### CODE REVIEW

**Comment by leo-smi** [comment]
pandas.io.json._normalize

I think it is pandas.io.json.json_normalize, see missed another .json

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.io.json.json_normalize.html

**Comment by emlazzarin** [comment]
@leo-smi This code only uses the `nested_to_record` function in that module and the code works, so I'm not sure there's any issue. Did you notice something wrong?

**Comment by leo-smi** [comment]
I'm sorry, the problem was the pandas version (0.22 google colab), I have the newst panda version now and it's working fine.

**Comment by dreyco676** [comment]
Should we add a requirement in the setup.py for this?


________________________________

**Comment by leo-smi** [comment]
I think it's a good idea because is not that obvious for those who will use it for the first time

**Comment by emlazzarin** [comment]
There's little harm in it, so I committed it to master: https://github.com/GeneralMills/pytrends/commit/16492e1610b87cec8248c3c79a0bd97cfb905bee

**Pull request merged**
