### PR TITLE
Getting daily data from Google Trends

### PR DESCRIPTION
**Pull request by Salompas**
I completely modified the script `dailydata.py`.
It can now be imported and provides a function `getDailyData` which fetches daily data for a single word. It uses a better method for dealing with scaling issues, see [this article](http://bit.ly/trendsscaling).
The code is well documented, has type hints and is PEP8 compliant.

Please let me know what you think. I hope this a good addition to the project and will help other users.
Let me know if there are modifications I could implement to make it mergeable.

### CODE REVIEW

**Comment by dsgerbc** [comment]
This is not really a comment on your code, but this seems like the place on the internet to comment on this. I'm wondering if you ever looked at stability of the historical data pulled via your (or any other method) on different days.  

I'm finding that the daily data from two different overlapping sub-samples with the same peak varies wildly (and more worryingly, the distribution of deviations looks quite skewed).  I think a reliable google trends data need some kind of averaging of the same request done over time, but I'm not finding anyone actually doing it.

**Comment by Salompas** [comment]
I agree, no matter which way you pull the data out of Google Trends you can get different results. 
I've been using the code with a colleague and we noticed that requests for the same word at the beginning of 2004 will sometimes result in no data available for a few days and at other times it will return a few data points.
I have tried obtaining the data via overlapping sub-samples before but I ran into the issue where the overlaps did not match each other. If I remember correctly I had overlaps of about 2 months (daily data) and a lot of the times not a single data point in this overlap matched.

Having said that, the problem is that we do not know how Google is cleaning, scaling and displaying their data, so it is quite hard to fix it.
As you said, a possible solution would be to average the values across different fetches.
The only problem with that is that depending on how many words you want to use will have a big impact on how much time it will take to fetch your data due to Google limiting the API usage.

**Comment by Salompas** [comment]
I ended up adding this file as a standalone package to facilitate installing: https://github.com/Salompas/pytrends-daily
Feel free to make suggestions!

**Comment by dsgerbc** [comment]
I'm okay with data being somewhat different if I understood how it came about. Google does not give us complete data but an allegedly random subsample. What bugs me is that these subsamples seem to change for all dates if you add just one more day to your request range. What bugs me more is that the changes do not appear to be normally distributed. But enough of rambling.  I'll play with your new package over a few days and maybe post something about results variability in comments.
Cheerz.

**Pull request merged**
