### PR TITLE
Support passing parameters to requests

### PR DESCRIPTION
**Pull request by gdoron**
Raise exception if there are no more proxies left (currently horrifically the request will go out without a proxy!)
Updated and fixed the readme

### CODE REVIEW

**Comment by gdoron** [comment]
Also (but not just) solves #382

**Comment by gdoron** [comment]
@emlazzarin any chance you can review this pull request?
I'm not 100% sure who is\are the maintainers of this repo.

**Comment by emlazzarin** [comment]
Looks good to me, although I haven't tested it. Thank you!

**Comment by gdoron** [comment]
@emlazzarin any chance you can also upload a new version to pypi so we can use it?
I still use my fork, which is not ideal.

Thanks buddy

**Comment by emlazzarin** [comment]
Done.

Sent via Superhuman ( https://sprh.mn/?vip=emlazzarin@gmail.com )

**Pull request merged**
