### PR TITLE
Dsgerbc try except

### PR DESCRIPTION
**Pull request by dsgerbc**
Hello. This is my attempt to resolve issues like #369
The code has no way of handling time-out exceptions. To do so, every interaction with the request library has been changed to try/except. To make it very simple, I just raise the error to be handled up stream.

Seems to have helped me scape continuously, changing VPNs on errors, which previously required manual restarts.

### CODE REVIEW

**Comment by emlazzarin** [comment]
@MaxGhenis — how do you feel about this?

**Comment by MaxGhenis** [comment]
Could you clarify what the code does? Isn't
```
try:
    ... code ...
except Exception:
    raise
```
just the equivalent of `... code ...`?

If it does something different, IMO it'd be good to catch a specific exception type. If there's a way to reproduce the issue, that'd help add a test for it that this PR resolves.

**Comment by dsgerbc** [comment]
I'm not an expert on error handling, but without try/except in those places
pytrends crashes out on socket timeouts even if I have try/except on things
like TrendReq(...) or getinterestovertime(..) in my main code.  Maybe the
underlying library doesn't handle socket timeouts or something. With
try/except in requests.py, I can catch those timeouts and act upon them
within the code.

The simple check would be to use the example in the package, then have
try/except it, put it in a loop, run it, disconnect the internet while it's
running and see if your exception code catches it.  Mine doesn't, unless
every interaction inside request.py with the requests library is
try/except'd.

**Comment by MaxGhenis** [comment]
I'm also not an expert in error handling or the `requests` package, but I find it odd that this would do anything, given this test:
```
In [1]: try: 
   ...:     1/0 
   ...: except Exception: 
   ...:     raise 
   ...:                                                                                                                                                                                                                                      
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-1-29cf2e5b06c4> in <module>
      1 try:
----> 2     1/0
      3 except Exception:
      4     raise
      5 

ZeroDivisionError: division by zero

In [2]: 1/0                                                                                                                                                                                                                                  
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-2-9e1622b385b6> in <module>
----> 1 1/0

ZeroDivisionError: division by zero
```

If this works, it seems like adding code to just catch the error in a single place, and then calling that code as needed, would be preferable. As-is, I think some of this PR is duplicative of the `try` in `get_data`, which is called elsewhere.

Up to the maintainers, but I'd recommend starting with an issue where you can more fully document the problems you're encountering, ideally reproducibly, and then we could discuss optimal fixes there (hopefully could be something simple in the `requests` package itself).

**Comment by dsgerbc** [comment]
To be honest, this feels like a bug somewhere either in requests or urllib3
libraries.

Here's a summary of what I was doing:
I'm gathering a ton of trends data, feeding google a few requests per
minute, frequently hopping proxies/vpns.  There are try/except structures
on all of my interactions with pytrends (init, buildpayload,
interestovertime etc), with any error followed by a change of server.
The code would still fail after an hour or two, generally with a
socket.timeout error or some other socket error. The try/except *should* be
catching those, but it wasn't.
So, I put those try/except into request.py to try to catch those there for
diagnostic purposes and somehow it did. And with try/except there, my own
try/except started working.
I've since ran the code for like a week with no breaks.

So, I have no clue why it worked, and I don't have a good example to test
this on cause the error is intermittent.

**Comment by emlazzarin** [comment]
I'm going to close this because I'm quite sure it doesn't actually do anything.

**Pull request closed without merging**
