### PR TITLE
Adapt the HTTP calls to the latest changes in Google Trends API

### LINKED ISSUE #566: new version of google trends not compatible whit pytrend  4.9.0
hi dear Eddy Lazzarin
In recent days, Google Trends has made changes in its service.
I think that the new version of google trends is not compatible with Pytrends 4.9.0
Please check the issue.
for more information, I added python stack trace of error.
Capture

best regards
ithabibi

### PR DESCRIPTION
**Pull request by Terseus**
Google Trends slightly changed its HTTP requests calls:

- the "get cookie" request changed its URL, needed now an extra "explore/"; this was the main reason of the premature 429 error responses.
- the "widgets" request is now POST instead of GET.

Before this change the requests returned almost consistently 429 error responses, now it returns results again.

Fixes #566, #567, #561

### CODE REVIEW

**Review by akash-ai — CHANGES_REQUESTED** [review]
Please do the following changes.

**Comment by Michae94** [comment]
Hey there, 

> - the "widgets" request is now POST instead of GET.


Why did you add this change in addition to the first one ?

**Comment by Terseus** [comment]
Hi @Michae94,

Because that's how the Google Trends website behaves, I guess the most secure way to prevent to be blocked is to mimic the website.

**Comment by DamianDavid** [comment]
Hi @Terseus , thanks for sharing this solution.
I applied the 'get cookie' step and It works fine when I run the codes from Jupyter, but it still shows the error message when running from https://datalore.jetbrains.com/ which is a web platform I use to schedule scripts. Could it be because I still need to execute the step two 'widgets'?

**Comment by Terseus** [comment]
Hi @DamianDavid,

I don't recommend you using the `GetGoogleCookie` outside of the `TrendReq` class.

Try to adhere to this workflow:

* create a new `TrendReq` object.
* call `build_payload`.
* call the method needed to obtain the information you want (e.g. `interest_over_time`).

If in doubt on how to use a specific method, [take a look at the tests](https://github.com/GeneralMills/pytrends/blob/master/tests/test_request.py).

**Comment by josh-ashkinaze** [comment]
Hi any update on merging this?

**Review by emlazzarin — APPROVED** [review]

**Comment by jabeztadesse** [comment]
Is this resolved?

**Pull request merged**
