### PR TITLE
major refactor of package (api breaking)

### PR DESCRIPTION
**Pull request by bdewilde**
This isn't merge-ready, I think, but it's to put you on notice and hopefully iterate towards a mutually satisfying result.

Changes:
- added `compat.py` module for Py2/3 compatibility imports, then used throughout other modules
- split csv data parsing code into `parse.py` module
- split google connection code into `connect.py` module
- added central, user-facing `pytrends.py` module, with key `GoogleTrends` interface class; changed methods that users call, from `request_report` to `query` and `save_csv` to `save_data`, which also have different function arguments that are, I think, more Python- and user-friendly
- fixed several bugs for Py2/3 compatibility
- user agent is randomized before every call to google
- added example script, `multiterm_query.py` to show off new interface options

### CODE REVIEW

**Comment by dreyco676** [comment]
You aren't working on the actual request method are you? If I wanted to work on changing that over to using the the Requests module tonight its not going to be a huge merge issue for you is it?

**Comment by bdewilde** [comment]
I factored all of the "connect to Google" code out into the `connect.py` module, so any changes under-the-hood will be easy to merge into this branch. I say go for it! Requests is so much nicer to work with.

**Comment by dreyco676** [comment]
Hey didn't get to this tonight. I go on vacation for a week so I won't have access to do pull requests and what not. Just an FYI.

**Comment by bdewilde** [comment]
Hey @dreyco676, I've been swamped, so I've not had a chance to work on this. It's not forgotten, but still back-burnered for the next couple weeks. Thanks for your patience!

**Comment by dreyco676** [comment]
I made some minor changes. I'll probably work on the change to requests in the next week.

**Comment by ravimevcha** [comment]
I tried using this file, however I m getting error "SystemError: Parent module '' not loaded, cannot perform relative import"

how do I resolve this?

**Comment by bdewilde** [comment]
Hi @ravimevcha, this is a branch that I never totally finished, so I wouldn't recommend using it — unless you want to finish it. :wink: As for the `relative import` error — gosh, that sounds like a Py2/3 compatibility issue and/or weirdness in the way that modules are imported.

**Comment by dreyco676** [comment]
A ton has changed since this was written. I think you'd need to totally redo what you were working on. Hopefully you'll get some time in the future.

**Pull request closed without merging**
