### PR TITLE
Migrate the test suite to vcrpy

### LINKED ISSUE #503: request for tests
Merging PRs is difficult for the maintainers because of a lack of robust tests. If somebody writes a broad set of tests, it will significantly improve the ability to merge updates with less risk.

Thank you for your help!

### PR DESCRIPTION
**Pull request by Terseus**
Fixes #503 

Using vcrpy now we can deterministically test the backend responses without making any real request.
This have a lot of advantages:
* Removes false negatives or test skipped for 429 responses.
* The tests are much faster now, all the 23 tests are executed in about 1 second in my PC.
* Allow to refactor anything that doesn't involve a change in the requests made.
* If the backend response changes we can regenerate the vcrpy cassettes with `pytest --record-mode=rewrite`.

There are some gotchas though:
* The backend can be unpredictable when asking for shorter timeframes (e.g. 10 days) so we chose to do yearly requests in almost all the tests.
* Due to the above the results to check can be quite big, therefore we don't compare the full result, instead we test the first and last rows, and the length of the result.
* There is *a lot* of YAML code now with the generated cassettes, I've tried to make Github ignore them by marking them with `linguist-vendored` in `.gitattributes` (see [linguist doc](https://github.com/github/linguist/blob/master/docs/overrides.md#vendored-code) and [this Stackoverflow response](https://stackoverflow.com/a/49899457/648661)) but we will not know if it works until the change is merged and some days have passed.
    * Alternatively we can merge only the first two commits in a separate PR, let pass some time and come back to this PR to see if it worked.
* Writing new tests require some knowledge not documented right now:
    * By default `pytest-recording` is executed with `--record-mode=none` so any new test without a cassette fails, this is intended to prevent generate cassettes unavertidely; to generate a new cassette you need to use `--record-mode=once`.
    * The cassette must be deleted after any change that requires modifying the requests made to the backend, and the error message may not communicate this clearly enough to anyone who doesn't know vcrpy.

### CODE REVIEW

**Comment by Terseus** [comment]
@emlazzarin 
Please note, I don't consider this 100% finished until we add some doc to how to write/maintain/use the test suite, however I don't know if we should simply add it to the `README.md` or if we want to create a `CONTRIBUTING.md` file along with more content, what do you prefer?

**Comment by emlazzarin** [comment]
Looks good. I think the additional size is acceptable.

Is comparing the full results very slow? Is that why we only check the first+last+size?

Let’s link from the README to a new CONTRIBUTING file we can start from scratch, just so the doc has the freedom to be as expansive as necessary.

**Comment by Terseus** [comment]
@emlazzarin

> Is comparing the full results very slow? Is that why we only check the first+last+size? 
No, is because the expected result variables can become quite big because we ask for a year of data, something I did because the daily data from the API is not trustworthy and I fear it might change.
Maybe I was paranoid and we can change the tests them to ask for a week of data or so and compare the full results, then we can get rid of the `ExpectedResponse` class.
What do you think?

> Let’s link from the README to a new CONTRIBUTING file we can start from scratch, just so the doc has the freedom to be as expansive as necessary.
Perfect, do you want me to start it with info about working with the test suite in this PR?

**Comment by Terseus** [comment]
Ok, I reduced the date ranges in the tests where we can use daily data but that was only 5 tests, with all the other I don't think is worth comparing the full result for not hardcoding DataFrames of between 25 and 250 rows.
I think it's okay right now.

**Pull request merged**
