### PR TITLE
fix language option

### PR DESCRIPTION
**Pull request by nickyungyung**
Bug fixed for related_topics()

### CODE REVIEW

**Comment by dabdada** [comment]
You sure that the hl param is all we need? Please check my PR #260 (sorry did not see this one here is existing). I needed to set the accept-language header (which is a good Idea in general), to fix this. According to the corresponding issue #259 the acceptence-header seems mendatory.

**Comment by dreyco676** [comment]
Thanks for the PR

**Comment by dreyco676** [comment]
Could you resubmit a PR, I just pulled in one before this.

**Comment by dabdada** [comment]
@dreyco676 can you check #260 ? I guess this solves the same problem. The param hl did not do the trick for me.

**Pull request merged**
